CREATE TABLE "civil_war_orphans" (
	"id" serial PRIMARY KEY NOT NULL,
	"family_name" varchar(200),
	"given_name" varchar(200),
	"aliases" varchar(500),
	"birth_date" varchar(100),
	"arrival" varchar(100),
	"departure" varchar(100),
	"scholarships" varchar(500),
	"assignments" varchar(500),
	"situation_1878" varchar(500),
	"assignment_scholarship_year" varchar(100),
	"references" text,
	"comments" text,
	"birth_date_original_text" text,
	"birth_date_uncertain" varchar(10),
	"birth_date_clean" varchar(100),
	"arrival_original_text" text,
	"arrival_uncertain" varchar(10),
	"arrival_at_lincoln" varchar(100),
	"departure_original_text" text,
	"departure_uncertain" varchar(10),
	"departure_at_lincoln" varchar(100),
	"departure_from_lincoln" varchar(100),
	"created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);
