import { headers } from 'next/headers';

/**
 * Get the nonce from request headers
 * This nonce is generated by the middleware and used for CSP
 */
export async function getNonce(): Promise<string> {
  const headersList = await headers();
  return headersList.get('x-nonce') ?? '';
}
