import { headers } from 'next/headers';

/**
 * Get the nonce from request headers
 * This nonce is generated by the middleware and used for CSP
 */
export function getNonce(): string {
  const headersList = headers();
  return headersList.get('x-nonce') ?? '';
}
